name: griya
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_skill: ^0.2.6
  flutter:
    sdk: flutter
  # Pustaka lokalisasi bahasa resmi pendukung penanggalan Indonesia
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: 1.0.4

  # REVISI HARMONIS: Kumpulan versi AndroidX murni yang terbukti klop satu sama lain
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.1
  firebase_database: ^11.0.1
  firebase_storage: ^12.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
